name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: npm
      - name: npm ci
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: run build
        run: npm run build:with-font
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_KEY }}
          known_hosts: ${{ secrets.STAGING_KNOWN_HOSTS }}
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: Deploy
        run: rsync -e ssh --rsync-path='sudo rsync' -rltpzhv --delete ./dist ${{ secrets.STAGING_DEPLOY_USER }}@${{ secrets.STAGING_DEPLOY_HOST }}:${{ secrets.STAGING_DEPLOY_RSYNC_DESTINATION }}
